training:
  unroll_length: 20
  batch_size: 32
  total_steps: 200_000_000
  entropy_cost: 0.01
  baseline_cost: 0.5
  discounting: 0.99
  learning_rate: 0.0006
  alpha: 0.99
  momentum: 0.0
  epsilon: 0.01
  grad_norm_clipping: 40.0
env:
  task: 'PongNoFrameskip-v4'
model:
  lstm: false
run:
  force_rank_0: learner
  tasks:
    learner:
      requirements:
        cpus: 8
        gpus: 1
      processes: 1
    actor:
      requirements:
        cpus: 2
      processes: 32 
